version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
    volumes:
      - ./resources:/app/resources
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
      - DEFAULT_M3U_PATH=resources/default.m3u
      - EPG_XML_PATH=https://epgshare01.online/epgshare01/epg_ripper_ES1.xml.gz
    restart: unless-stopped
  acestream-http-proxy:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream-http-proxy
    restart: unless-stopped
    #Descomentar las siguientes líneas si quieres permitir la ejecución desde internet. En caso contrario, solo funcionará en tu red local 
    #environment:
    #  - ALLOW_REMOTE_ACCESS=yes
    ports:
      - 6878:6878
